[global]
#   disable password sync
    pam password change = no
    unix password sync = no

#   disable printers
    load printers = no
    printcap name = /dev/null
    printing = bsd

[homes]
#   default enable home writable share
    comment = Home Directories
    browsable = yes
    writable = yes
    create mask = 700
    directory mask = 700

[printers]
#   disable printers
    comment = Disabled
    path = /dev/null
    printable = no
    browsable = no

[print$]
#   disable printers
    comment = Printer Drivers (disabled)
    path = /dev/null
    browsable = no
    read only = yes

