[global]
    load printers = no
    printcap name = /dev/null
    printing = bsd

[printers]
    comment = Disabled
    path = /dev/null
    printable = no
    browsable = no

[print$]
    comment = Printer Drivers (disabled)
    path = /dev/null
    browsable = no
    read only = yes

